[package]
name = "game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game"


[dependencies]
bevy = "0.9"
bevy_prototype_lyon = "0.7"
bevy_rapier2d = "0.20"
physic-objects = { path = "../physic-objects"}